# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6533505ab77f19d323bda9ab5f0b3447f2b2c3a42282dd8a04f84f421b0f32d342b382bba1ef2e9197d017348b891b5022f7d69ac37a0e51de60d6e02a4df90b

test:
  secret_key_base: d9d8087c5fc2b5f2fbee1ee3e75dad529ccd66e0d40136c453086b386c2c3c995aa57480815115f54abdb5184e6e4f404feab3846b90d42c7185019eb8d36395

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
